### ISSUE TITLE
Missing data file - xtGDPlong.dta

### ISSUE THREAD

**Issue by MargareeMan** [jlevendi/Time-Series-Econometrics#1]
I cannot find the xtGDPlong.dta file and I am very interested in your Chapter 13 examples.

**Comment by jlevendi** [comment]
Thanks for letting me know. I've just uploaded a fresh batch of files. Please let me know if any other files are missing.

**Comment by MargareeMan** [comment]
Thanks greatly.  I do not know how to close the issue!?
